services:
  devfreela.api:
    image: ${DOCKER_REGISTRY-}devfreelaapi
    build:
      context: .
      dockerfile: DevFreela.API/Dockerfile

  devfreeladb:
   image: mcr.microsoft.com/mssql/server

volumes: 
  sqlserver_data:
